import openai
import json
import os
from services.configLoader import load_config
from services.setupLogger import setup_logger

logger = setup_logger(__name__, f"logs/stockAnalyzer.log")

openai.api_key = load_config("openAIKey")

def generate_report(ticker, name, df, prompt_template):
    """
    Generates a report based on the prompt.
    Args:
        ticker (str): The ticker symbol of the stock or ETF.
        name (str): The name of the security.
        df (pd.DataFrame): The DataFrame to be analyzed.
        prompt_template (str): A prompt with placeholders for {ticker}, {name}, {data_json}.
    Returns:
        str: The response generated by GPT.
    """
    try:
        summary_data = df.tail(5).to_dict()
        data_json = json.dumps(summary_data, indent=2)

        # Replace placeholders in the prompt
        prompt = prompt_template.format(ticker=ticker, name=name, data_json=data_json)

        logger.debug(f"Sending prompt to OpenAI:\n{prompt[:10]}...")  # Log only the first 500 characters

        response = openai.ChatCompletion.create(
            model="gpt-4",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7
        )

        return response['choices'][0]['message']['content']

    except Exception as e:
        logger.error(f"Error generating report: {e}")
        return f"Error generating report: {e}"
